### ISSUE TITLE
implement BIP173 - SegWit

### ISSUE THREAD

**Issue by gits7r** [Bit-Wasp/bitcoin-lib-php#115]
We need sooner rather than later to implement BIP173 (native SegWit addresses) as well as support for SegWit transactions (native and nested in P2SH). Does bitcoin-php or secpk256k1 php need changes for these purposes also?

**Comment by afk11** [comment]
Hi, bitcoin-lib-php isn't maintained anymore, but both BIP173 and segwit transactions are supported in https://github.com/Bit-Wasp/bitcoin-php

**Comment by gits7r** [comment]
Oh, thanks for the heads up. So basically bitcoin-php includes and maintains everything in bitcoin-lib-php and secp256k1-php, so I can only use that?

**Comment by afk11** [comment]
Yep, it covers everything (tho the API is a bit different), and is the only one of the two libs that can use the extension secp256k1-php. The examples should hopefully be enough if you need to switch, or just poke me in an issue

**Comment by afk11** [comment]
Adding some examples for the different address types: https://github.com/Bit-Wasp/bitcoin-php/pull/536

**Comment by gits7r** [comment]
We're all good here. Thanks @afk11
