### ISSUE TITLE
Class mdanter/phpecc update

### ISSUE THREAD

**Issue by FabioCarpi** [Bit-Wasp/bitcoin-lib-php#46]
Some classes puts the adapter from the last to the first

**Comment by afk11** [comment]
This doesn't seem to affect master. I have set the version at 0.2.0 for this library, I'll update it soon though.

**Comment by afk11** [comment]
@FabioCarpi https://github.com/Bit-Wasp/bitcoin-lib-php/pull/59 will bring the library up to date! I'll keep an eye out for 0.3.0 when it comes out

**Comment by FabioCarpi** [comment]
thanks. im anxious

**Comment by afk11** [comment]
Hey @FabioCarpi I saw your hangouts invite, but for some reason I can't get your email from that. I actually use another email for hangouts, sorry for the confusion :/ Send me an email at the last one
