### ISSUE TITLE
create multi address

### ISSUE THREAD

**Issue by syrakozz** [Bit-Wasp/bitcoin-lib-php#72]
how i  can create multi btc address

**Comment by rubensayshi** [comment]
hmm, there's a bunch of https://github.com/Bit-Wasp/bitcoin-lib-php/tree/master/examples but they're actually a bit old, gimme a few min and I'll add a better example

**Comment by rubensayshi** [comment]
I updated the multisig example, you can see it here: https://github.com/blocktrail/bitcoin-lib-php/blob/multisig-example/examples/multisig.php (did a PR to have @afk11 merge it in)

**Comment by syrakozz** [comment]
+1

**Comment by afk11** [comment]
Merged, thanks!
