### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by thecrm** [Bit-Wasp/bitcoin-lib-php#88]
Parse error: syntax error, unexpected '[', expecting ')' in /..../mpk/tests/BIP32Test.php on line 39

**Comment by rubensayshi** [comment]
this library is PHP 5.4+

**Comment by rubensayshi** [comment]
also I recommend you learn how composer works and use composer to install libraries (including this one), it will install the rest of the dependancies and also check for requirements such as the PHP version.

**Comment by afk11** [comment]
Definitely want to echo @rubensayshi's advice.. Use composer, it takes away these problems. I noticed on Reddit you wanted to avoid gmp. Are you on a shared host, or is there a reason you might not be able to install more software?

**Comment by afk11** [comment]
Will close this, as the error in this case is purely the PHP version.
